// Date: 2016/11/27 22:52:27
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package yousui115.bonfire.client.render;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;


public class ModelPot extends ModelBase
{
  //fields
    ModelRenderer BodyTop;
    ModelRenderer BodyUnder;
    ModelRenderer Edge;
    ModelRenderer Lid;
    ModelRenderer LidHandle;
    ModelRenderer Nozzle;
    ModelRenderer Handle1;
    ModelRenderer Handle2;
    ModelRenderer Handle3;

  public ModelPot()
  {
    textureWidth = 128;
    textureHeight = 128;

      BodyTop = new ModelRenderer(this, 0, 30);
      BodyTop.addBox(-7F, 0F, -7F, 14, 10, 14);
      BodyTop.setRotationPoint(0F, 0F, 0F);
      BodyTop.setTextureSize(128, 128);
      BodyTop.mirror = true;
      setRotation(BodyTop, 0F, 0F, 0F);
      BodyUnder = new ModelRenderer(this, 0, 0);
      BodyUnder.addBox(-8F, 0F, -8F, 16, 14, 16);
      BodyUnder.setRotationPoint(0F, 10F, 0F);
      BodyUnder.setTextureSize(128, 128);
      BodyUnder.mirror = true;
      setRotation(BodyUnder, 0F, 0F, 0F);
      Edge = new ModelRenderer(this, 0, 54);
      Edge.addBox(-8.5F, 0F, -8.5F, 17, 1, 17);
      Edge.setRotationPoint(0F, -1F, 0F);
      Edge.setTextureSize(128, 128);
      Edge.mirror = true;
      setRotation(Edge, 0F, 0F, 0F);
      Lid = new ModelRenderer(this, 0, 72);
      Lid.addBox(-6.5F, 0F, -6.5F, 13, 2, 13);
      Lid.setRotationPoint(0F, -3F, 0F);
      Lid.setTextureSize(128, 128);
      Lid.mirror = true;
      setRotation(Lid, 0F, 0F, 0F);
      LidHandle = new ModelRenderer(this, 0, 87);
      LidHandle.addBox(-2F, -2F, -2F, 4, 2, 4);
      LidHandle.setRotationPoint(0F, -3F, 0F);
      LidHandle.setTextureSize(128, 128);
      LidHandle.mirror = true;
      setRotation(LidHandle, 0F, 0F, 0F);
      Nozzle = new ModelRenderer(this, 64, 0);
      Nozzle.addBox(0F, 0F, 0F, 3, 17, 3);
      Nozzle.setRotationPoint(0F, 5F, -16F);
      Nozzle.setTextureSize(128, 128);
      Nozzle.mirror = true;
      setRotation(Nozzle, 0.5205006F, 0F, 0F);
      Handle1 = new ModelRenderer(this, 64, 20);
      Handle1.addBox(0F, 0F, 0F, 1, 1, 7);
      Handle1.setRotationPoint(0F, 4F, 7F);
      Handle1.setTextureSize(128, 128);
      Handle1.mirror = true;
      setRotation(Handle1, 0F, 0F, 0F);
      Handle2 = new ModelRenderer(this, 76, 0);
      Handle2.addBox(0F, 0F, 0F, 1, 10, 1);
      Handle2.setRotationPoint(0F, 5F, 13F);
      Handle2.setTextureSize(128, 128);
      Handle2.mirror = true;
      setRotation(Handle2, 0F, 0F, 0F);
      Handle3 = new ModelRenderer(this, 64, 28);
      Handle3.addBox(0F, 0F, 0F, 1, 1, 7);
      Handle3.setRotationPoint(0F, 15F, 7F);
      Handle3.setTextureSize(128, 128);
      Handle3.mirror = true;
      setRotation(Handle3, 0F, 0F, 0F);
  }

  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    BodyTop.render(f5);
    BodyUnder.render(f5);
    Edge.render(f5);
    Lid.render(f5);
    LidHandle.render(f5);
    Nozzle.render(f5);
    Handle1.render(f5);
    Handle2.render(f5);
    Handle3.render(f5);
  }

  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

  /**
   * ■フタをカタカタさせる
   * @param x
   * @param z
   */
  public void setLidRotation(float x, float z)
  {
      Lid.rotateAngleX = x;
      Lid.rotateAngleZ = z;
      LidHandle.rotateAngleX = x;
      LidHandle.rotateAngleZ = z;
  }
}
